In [107]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [108]:
torch.__version__

'2.0.0+cu117'

In [109]:
#scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [110]:
scalar.ndim

0

In [111]:
#get tensor back as Python int
scalar.item()

6

In [112]:
vector = torch.tensor([1,2,3,4,5])

In [113]:
vector.ndim

1

In [114]:
vector.shape

torch.Size([5])

In [115]:
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [116]:
MATRIX.ndim

2

In [117]:
MATRIX[0]

tensor([1, 2, 3])

In [118]:
MATRIX[1]

tensor([4, 5, 6])

In [119]:
MATRIX.shape

torch.Size([2, 3])

In [120]:
TENSOR = torch.tensor([
    [[1,2,3], [1, 5, 10]], 
    [[4,5,6], [6, 2, 1]], 
    [[7,8,9], [9, 3, 2]]
    ])
TENSOR

tensor([[[ 1,  2,  3],
         [ 1,  5, 10]],

        [[ 4,  5,  6],
         [ 6,  2,  1]],

        [[ 7,  8,  9],
         [ 9,  3,  2]]])

In [121]:
TENSOR.ndim

3

In [122]:
TENSOR.shape

torch.Size([3, 2, 3])

Why random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors fill of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [123]:
# Create a random tensor
random_tensor = torch.rand(3, 2, 5)
random_tensor

tensor([[[0.1645, 0.0283, 0.0435, 0.4326, 0.8997],
         [0.8130, 0.4902, 0.1241, 0.6331, 0.9987]],

        [[0.2719, 0.3070, 0.3632, 0.3820, 0.4681],
         [0.4032, 0.2522, 0.1803, 0.9121, 0.7144]],

        [[0.9575, 0.5180, 0.0731, 0.8748, 0.5302],
         [0.0050, 0.0421, 0.6500, 0.4766, 0.7756]]])

In [124]:
random_tensor.ndim

3

In [125]:
10 * 10 * 10

1000

In [126]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [127]:
zeroes = torch.zeros(size=(3, 5))
zeroes

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [128]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [129]:
ones.dtype

torch.float32

In [130]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
one_to_thousand = torch.arange(start=0, end=1000, step=77)
one_to_thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [132]:
new_tensor = torch.zeros_like(one_to_thousand)
new_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [133]:
import torch
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=None, 
                               device=None, requires_grad=False)# tracking gradients
float_32_tensor

tensor([1., 2., 3.])

In [134]:
float_32_tensor.dtype

torch.float32

### Tensor Datatypes

**Note** Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. tensor not on the right device(one lives in cpu and one in gpu for example)

In [135]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [136]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

In [137]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [138]:
float_32_tensor * int_32_tensor

tensor([1., 4., 9.])

### Getting information from tensor

1. Tensor not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. tensor not on the right device - to get a device from tensor, can use `tensor.device`

In [139]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[9.2542e-01, 5.6959e-01, 8.4101e-01, 3.0945e-01],
        [6.5738e-04, 8.5691e-01, 9.9374e-01, 8.4333e-01],
        [4.0638e-01, 5.7378e-01, 3.1047e-01, 9.9061e-01]])

In [140]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [141]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[9.2542e-01, 5.6959e-01, 8.4101e-01, 3.0945e-01],
        [6.5738e-04, 8.5691e-01, 9.9374e-01, 8.4333e-01],
        [4.0638e-01, 5.7378e-01, 3.1047e-01, 9.9061e-01]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


In [142]:
print(f"Device tensor is: {some_tensor.device}")

Device tensor is: cpu


In [143]:
more_tensor = torch.rand(3, 4, dtype=torch.float16)

In [144]:
more_tensor

tensor([[0.4570, 0.5278, 0.1929, 0.3271],
        [0.3691, 0.4492, 0.4336, 0.9731],
        [0.3120, 0.8950, 0.3906, 0.2305]], dtype=torch.float16)

In [145]:
more_tensor.dtype, more_tensor.shape

(torch.float16, torch.Size([3, 4]))

In [146]:
more_tensor.device

device(type='cpu')

### Manipulating tensors (tensor operations)

Tensor operation includes:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication

In [147]:
tensor = torch.tensor([1, 2, 3, 4, 5])
tensor + 10

tensor([11, 12, 13, 14, 15])

In [148]:
tensor * 10

tensor([10, 20, 30, 40, 50])

In [149]:
tensor - 10

tensor([-9, -8, -7, -6, -5])

In [150]:
torch.mul(tensor, 10)

tensor([10, 20, 30, 40, 50])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rule that performing matrix mul need to satisfy:
1. The ** inner dimensions ** must match, inner is the row and outer is the column
`(3, 2) @ (3, 2)` - won't work
`(2, 3) @ (3, 2)` - will work
`(3, 2) @ (2, 3)` - will work
2. The resulting matrix has the shape of the ** outer dimensions **
`(2, 3) @ (3, 2)` -> `(2, 2)`
`(3, 2) @ (2, 3)` -> `(3, 3)`

In [151]:
print(tensor, '*', tensor)
tensor * tensor

tensor([1, 2, 3, 4, 5]) * tensor([1, 2, 3, 4, 5])


tensor([ 1,  4,  9, 16, 25])

In [152]:
torch.matmul(tensor, tensor)

tensor(55)

In [153]:
1 * 1 + 2 * 2 + 3 * 3 + 4 * 4 + 5 * 5

55

In [154]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 235 µs, sys: 101 µs, total: 336 µs
Wall time: 252 µs


tensor(55)

In [155]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 94 µs, sys: 41 µs, total: 135 µs
Wall time: 92.3 µs


tensor(55)

In [156]:
tensor @ tensor

tensor(55)

### One of the most common errors in deep learning: shape errors

In [157]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [159]:
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [160]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

fix using transpose to change shape, it switches the axes of given tensor

In [163]:
tensor_B = tensor_B.T

In [164]:
tensor_B.shape

torch.Size([2, 3])

In [167]:
torch.matmul(tensor_B, tensor_A).shape

torch.Size([2, 2])

## Finding the min,max,mean,sum,etc(tensor aggregration)

In [168]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [169]:
torch.min(x), x.max()

(tensor(0), tensor(90))

note: torch.mean requires a tensor of float

In [174]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [175]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))