In [32]:
import torch

random_tensor = torch.rand(7, 7)

In [33]:
another_random_tensor = torch.rand(1, 7)

In [34]:
another_random_tensor = another_random_tensor.T

In [35]:
another_random_tensor.shape

torch.Size([7, 1])

In [36]:
torch.matmul(random_tensor, another_random_tensor)

tensor([[1.6249],
        [1.6406],
        [1.7639],
        [1.3974],
        [1.4691],
        [0.9267],
        [2.4269]])

In [37]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
another_random_tensor = torch.rand(1, 7)

random_tensor, another_random_tensor

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]))

In [38]:
another_random_tensor = another_random_tensor.T
another_random_tensor

tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])

In [39]:
torch.matmul(random_tensor, another_random_tensor)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [40]:
# random in gpu
cuda0 = torch.device('cuda:0')
GPU_RANDOM_SEED = 1234
torch.manual_seed(GPU_RANDOM_SEED)
cuda_random_tensor = torch.randn(3).to(cuda0)
cuda_random_tensor

tensor([ 0.0461,  0.4024, -1.0115], device='cuda:0')

In [41]:
cuda_random_tensor.device

device(type='cuda', index=0)

In [42]:
torch.manual_seed(GPU_RANDOM_SEED)
rand_tensor1_togpu = torch.rand(2, 3).to(cuda0)

torch.manual_seed(GPU_RANDOM_SEED)
rand_tensor2_togpu = torch.rand(2, 3).to(cuda0)

rand_tensor1_togpu, rand_tensor2_togpu

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [43]:
rand_tensor2_togpu = rand_tensor2_togpu.T
matmul_gpu_tensor = torch.matmul(rand_tensor1_togpu, rand_tensor2_togpu)

In [47]:
matmul_gpu_tensor

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [46]:
matmul_gpu_tensor.max(), matmul_gpu_tensor.min()

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [48]:
matmul_gpu_tensor.argmax(), matmul_gpu_tensor.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [50]:
last_rand_tensor = torch.rand(1, 1, 1, 10)
squeezed_last_rand_tensor = last_rand_tensor.squeeze()
squeezed_last_rand_tensor

tensor([0.2837, 0.6567, 0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665,
        0.7399])

In [51]:
RANDOM_SEED = 7
print(last_rand_tensor)
print(squeezed_last_rand_tensor)

tensor([[[[0.2837, 0.6567, 0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294,
           0.9665, 0.7399]]]])
tensor([0.2837, 0.6567, 0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665,
        0.7399])
