In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
torch.__version__

'2.0.0+cu117'

In [4]:
#scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [5]:
scalar.ndim

0

In [6]:
#get tensor back as Python int
scalar.item()

6

In [7]:
vector = torch.tensor([1,2,3,4,5])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([5])

In [10]:
MATRIX = torch.tensor([[1,2,3],
                       [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([1, 2, 3])

In [13]:
MATRIX[1]

tensor([4, 5, 6])

In [14]:
MATRIX.shape

torch.Size([2, 3])

In [15]:
TENSOR = torch.tensor([
    [[1,2,3], [1, 5, 10]], 
    [[4,5,6], [6, 2, 1]], 
    [[7,8,9], [9, 3, 2]]
    ])
TENSOR

tensor([[[ 1,  2,  3],
         [ 1,  5, 10]],

        [[ 4,  5,  6],
         [ 6,  2,  1]],

        [[ 7,  8,  9],
         [ 9,  3,  2]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([3, 2, 3])

Why random tensor?

Random tensors are important because the way many neural networks learn is that they start with tensors fill of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# Create a random tensor
random_tensor = torch.rand(3, 2, 5)
random_tensor

tensor([[[0.3730, 0.7426, 0.6180, 0.4034, 0.9227],
         [0.1091, 0.2836, 0.0803, 0.1883, 0.7851]],

        [[0.2656, 0.3320, 0.1146, 0.1124, 0.5928],
         [0.4340, 0.8522, 0.6995, 0.7838, 0.9974]],

        [[0.0461, 0.6049, 0.8561, 0.7235, 0.9156],
         [0.3599, 0.6316, 0.3940, 0.1239, 0.6695]]])

In [19]:
random_tensor.ndim

3

In [20]:
10 * 10 * 10

1000

In [21]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [22]:
zeroes = torch.zeros(size=(3, 5))
zeroes

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
one_to_thousand = torch.arange(start=0, end=1000, step=77)
one_to_thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
new_tensor = torch.zeros_like(one_to_thousand)
new_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
import torch
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=None, 
                               device=None, requires_grad=False)# tracking gradients
float_32_tensor

tensor([1., 2., 3.])

In [29]:
float_32_tensor.dtype

torch.float32

### Tensor Datatypes

**Note** Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. tensor not on the right device(one lives in cpu and one in gpu for example)

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

In [32]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([1., 4., 9.])

### Getting information from tensor

1. Tensor not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. tensor not on the right device - to get a device from tensor, can use `tensor.device`

In [34]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1775, 0.7903, 0.1064, 0.3174],
        [0.4477, 0.2093, 0.4499, 0.9886],
        [0.7584, 0.8636, 0.6807, 0.2473]])

In [35]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [36]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[0.1775, 0.7903, 0.1064, 0.3174],
        [0.4477, 0.2093, 0.4499, 0.9886],
        [0.7584, 0.8636, 0.6807, 0.2473]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


In [37]:
print(f"Device tensor is: {some_tensor.device}")

Device tensor is: cpu


In [38]:
more_tensor = torch.rand(3, 4, dtype=torch.float16)

In [39]:
more_tensor

tensor([[0.1479, 0.0552, 0.2031, 0.4570],
        [0.2075, 0.2139, 0.1284, 0.1870],
        [0.5156, 0.2334, 0.4668, 0.9429]], dtype=torch.float16)

In [40]:
more_tensor.dtype, more_tensor.shape

(torch.float16, torch.Size([3, 4]))

In [41]:
more_tensor.device

device(type='cpu')

### Manipulating tensors (tensor operations)

Tensor operation includes:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication

In [42]:
tensor = torch.tensor([1, 2, 3, 4, 5])
tensor + 10

tensor([11, 12, 13, 14, 15])

In [43]:
tensor * 10

tensor([10, 20, 30, 40, 50])

In [44]:
tensor - 10

tensor([-9, -8, -7, -6, -5])

In [45]:
torch.mul(tensor, 10)

tensor([10, 20, 30, 40, 50])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rule that performing matrix mul need to satisfy:
1. The ** inner dimensions ** must match, inner is the row and outer is the column
`(3, 2) @ (3, 2)` - won't work
`(2, 3) @ (3, 2)` - will work
`(3, 2) @ (2, 3)` - will work
2. The resulting matrix has the shape of the ** outer dimensions **
`(2, 3) @ (3, 2)` -> `(2, 2)`
`(3, 2) @ (2, 3)` -> `(3, 3)`

In [46]:
print(tensor, '*', tensor)
tensor * tensor

tensor([1, 2, 3, 4, 5]) * tensor([1, 2, 3, 4, 5])


tensor([ 1,  4,  9, 16, 25])

In [47]:
torch.matmul(tensor, tensor)

tensor(55)

In [48]:
1 * 1 + 2 * 2 + 3 * 3 + 4 * 4 + 5 * 5

55

In [49]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 275 µs, sys: 183 µs, total: 458 µs
Wall time: 377 µs


tensor(55)

In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 167 µs, total: 167 µs
Wall time: 132 µs


tensor(55)

In [51]:
tensor @ tensor

tensor(55)

### One of the most common errors in deep learning: shape errors

In [52]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [53]:
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [54]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

fix using transpose to change shape, it switches the axes of given tensor

In [55]:
tensor_B = tensor_B.T

In [56]:
tensor_B.shape

torch.Size([2, 3])

In [57]:
torch.matmul(tensor_B, tensor_A).shape

torch.Size([2, 2])

## Finding the min,max,mean,sum,etc(tensor aggregration)

In [58]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
torch.min(x), x.max()

(tensor(0), tensor(90))

note: torch.mean requires a tensor of float

In [60]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [61]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

the argmin and argmax gives you the index of of the min or max value item in the array

In [63]:
x.argmin()

tensor(0)

In [65]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an inpur tensor of a certain shape but leep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view if the input with dimensions permuted(swapped) in a certain way

In [10]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [11]:
#Add extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [12]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [13]:
#Chaging z change x(because a view share the samem memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [14]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [26]:
# torch squeeze, removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Removes the first array since it has only 1 dimension
x_squeezed = x_reshaped.squeeze()

print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

x = torch.zeros(2, 1, 2, 1, 2)
x.size()

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


torch.Size([2, 1, 2, 1, 2])

In [16]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [17]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [18]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [19]:
y = torch.squeeze(x, (1, 2, 3))

In [21]:
x_reshaped.shape

torch.Size([1, 9])

In [22]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
x_reshaped.squeeze().shape

torch.Size([9])

In [29]:
# torh unsqueece - adds a single dimension to a target tensor at a spesific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [30]:
# torch.permute . rearranges the dimensions of a target tensor in a spesified order
x_original = torch.rand(size=(244, 244, 3)) # height, width, colour_channel(in this case RGB)

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0

print(f"Prev shape: {x_original.shape}")
print(f"new shape: {x_permuted}")

Prev shape: torch.Size([244, 244, 3])
new shape: tensor([[[0.4851, 0.0574, 0.0076,  ..., 0.4896, 0.9471, 0.2914],
         [0.0650, 0.2955, 0.9220,  ..., 0.8565, 0.6200, 0.3233],
         [0.1923, 0.1853, 0.5780,  ..., 0.0939, 0.5479, 0.6985],
         ...,
         [0.8715, 0.9480, 0.9486,  ..., 0.3107, 0.6783, 0.8989],
         [0.7473, 0.9374, 0.5646,  ..., 0.4199, 0.1614, 0.0574],
         [0.0950, 0.8284, 0.2317,  ..., 0.2604, 0.5391, 0.1436]],

        [[0.6732, 0.6002, 0.9186,  ..., 0.2863, 0.4506, 0.7324],
         [0.7560, 0.3465, 0.6922,  ..., 0.9193, 0.7005, 0.0609],
         [0.3669, 0.0842, 0.4540,  ..., 0.6764, 0.4560, 0.0528],
         ...,
         [0.0300, 0.9630, 0.1344,  ..., 0.7599, 0.2111, 0.1181],
         [0.7892, 0.5731, 0.4370,  ..., 0.1143, 0.8493, 0.0029],
         [0.3632, 0.6391, 0.0468,  ..., 0.9304, 0.9984, 0.9920]],

        [[0.7326, 0.8917, 0.9564,  ..., 0.1826, 0.5707, 0.0435],
         [0.1076, 0.9952, 0.4010,  ..., 0.8798, 0.1859, 0.4593],
         

In [32]:
x_original[0, 0, 0] = 74032

In [36]:
x_permuted

tensor([[[7.4032e+04, 5.7433e-02, 7.6271e-03,  ..., 4.8960e-01,
          9.4711e-01, 2.9141e-01],
         [6.4959e-02, 2.9553e-01, 9.2197e-01,  ..., 8.5649e-01,
          6.1998e-01, 3.2335e-01],
         [1.9232e-01, 1.8526e-01, 5.7804e-01,  ..., 9.3885e-02,
          5.4786e-01, 6.9846e-01],
         ...,
         [8.7145e-01, 9.4803e-01, 9.4857e-01,  ..., 3.1067e-01,
          6.7826e-01, 8.9895e-01],
         [7.4732e-01, 9.3744e-01, 5.6461e-01,  ..., 4.1989e-01,
          1.6140e-01, 5.7420e-02],
         [9.5016e-02, 8.2844e-01, 2.3168e-01,  ..., 2.6043e-01,
          5.3909e-01, 1.4356e-01]],

        [[6.7324e-01, 6.0025e-01, 9.1856e-01,  ..., 2.8631e-01,
          4.5060e-01, 7.3239e-01],
         [7.5602e-01, 3.4655e-01, 6.9222e-01,  ..., 9.1934e-01,
          7.0045e-01, 6.0930e-02],
         [3.6695e-01, 8.4209e-02, 4.5399e-01,  ..., 6.7640e-01,
          4.5596e-01, 5.2842e-02],
         ...,
         [3.0002e-02, 9.6296e-01, 1.3442e-01,  ..., 7.5989e-01,
          2.110

In [34]:
x_permuted[0, 0, 0], x_original[0, 0, 0]

(tensor(74032.), tensor(74032.))

## Indexing (selecting data from tensor)

Indexing with PyTorch is similar to indexing with Numpy.

In [37]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [38]:
#Indexing tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [39]:
#index middle bracket
x[0][0]

tensor([1, 2, 3])

In [40]:
#indexing most inner bracket
x[0][0][0]

tensor(1)

In [41]:
x[0][2][2]

tensor(9)

In [47]:
#use : to select all of target dimension
x[0, :, 0]

tensor([1, 4, 7])

In [51]:
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensors and Numpy

Numpy is a popular scientific Python numerical computing library.
and because of this, pytorch gar functionality to interact with it
* Data in munpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [52]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [53]:
array.dtype

dtype('float64')

In [54]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [56]:
torch.from_numpy(array).type(torch.float32).dtype

torch.float32

In [57]:
# changing array, will it reflect
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [58]:
#Tensor to numpy array, still reflect type
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [59]:
# Change the tensor, will it reflect
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproduceability(to get the exact outcome in another setting)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

To reduce the randomness in nn and pytorch comes the concept of a ** random seed ** 
Essentially what the random seed does is "flavour" the randomness.

In [60]:
# Create 2 random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3872, 0.6667, 0.4768, 0.2107],
        [0.6553, 0.3054, 0.9951, 0.1759],
        [0.0348, 0.1144, 0.7645, 0.7657]])
tensor([[0.9408, 0.2400, 0.9565, 0.5258],
        [0.2412, 0.7260, 0.2677, 0.9491],
        [0.5193, 0.1695, 0.7127, 0.2850]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [65]:
#making a reproduceable tensor
RANDOM_SEED = 42

#use seed everytime if in notebook
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch object on the GPU(faster computation)

GPUs = faster computation thanks to cuda

## Check for GPU access with Pytorch

In [66]:
# check gpu access
torch.cuda.is_available()

True

In [67]:
torch.cuda.device_count()

1

In [68]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [69]:
device

'cuda'

In [70]:
# Count devices
torch.cuda.device_count()

1

In [71]:
# Create a tensor(default on gpu)
tensor = torch.tensor([1, 2, 3])

#Tensor not on gpu
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [72]:
# Move tensor to gpu (if available), this code will work regardless
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensor back to the CPU

In [77]:
# if tensor is on GPU, can't transform it to Numpy, have to make a copy and port it back into ram

# first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

In [80]:
tensor_back_on_cpu

array([1, 2, 3])

In [79]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')